#!/usr/bin/env python

import sys

if sys.stdin.isatty():
  print 'Input is empty. Usage: echo "foo\\nbar" | affix-lines pre|su [affix-]';
  sys.exit(1);

prefix=sys.argv[1] == 'pre'
suffix=sys.argv[1] == 'su'
affix=sys.argv[2]

for line in sys.stdin:
  trimmedLine = line.strip();

  if prefix:
    print affix + trimmedLine
  if suffix:
    print trimmedLine + affix
