#!/usr/bin/env python

import sys

if sys.stdin.isatty():
  print 'Input is empty. Usage: echo "foo\\nbar" | format-lines string{0}to{0}format';
  sys.exit(1);

stringToFormat=sys.argv[1]

for line in sys.stdin:
  trimmedLine = line.strip();

  print stringToFormat.format(trimmedLine)
