#!/usr/bin/env python

import sys

if sys.stdin.isatty():
  print 'Input is empty. Usage: echo "foo\\nbar\\nfoo" | unique-list';
  sys.exit(1);

uniqueList = []
for line in sys.stdin:
  trimmedLine = line.strip()

  if trimmedLine not in uniqueList:
    uniqueList.append(trimmedLine)
    print trimmedLine
